language: go

go:
  - 1.4
  - tip

install:
    - go get -v github.com/onsi/ginkgo/ginkgo
    - go get -v github.com/onsi/gomega
    - go get -v -t ./...
    - export PATH=$PATH:$HOME/gopath/bin

script: ginkgo -r --randomizeAllSpecs --randomizeSuites --trace --compilers=2

services: mongodb

notifications:
  email:
    on_success: change
    on_failure: always

  irc:
    channels:
      - "chat.freenode.net#lsms"
    on_success: change
    on_failure: always
